apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob
  namespace: nginx
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          name: hello
          labels:
            app: hello
        spec:
          containers:
          - name: hello
            image: busybox
            command:
            - /bin/sh
            - -c
            - echo "Backup started" && sleep 30 && echo "Backup finished"
            - mkdir -p /data/backup
            - echo "Backup data" > /data/backup/backup.txt
            - echo "Backup completed"
            volumeMounts:
            - name: local-storage
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: local-storage
            persistentVolumeClaim:
              claimName: local-pvc
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1 
