apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-task
    spec:
      containers:
      - name: batch-task
        image: busybox
        command: ["sh",  "-c", "echo Hello from the Kubernetes cluster! && sleep 30"]
      restartPolicy: Never
