apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    type: local
  namespace: nginx
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    - path: /mnt/data
      type: DirectoryOrCreate